periodicity = "10s"
host = "localhost"
port = 8050

[[checks]]
type = "network"
url = "http://localhost/ping"

[[checks]]
type = "network"
url = "tcp://%2Ftmp%2Fapp.sock/ping"

[[checks]]
type = "network"
url = "udp://%2Ftmp/app.sock/ping"

[[checks]]
type = "command"
exec = "ls -la"

[[checks]]
type = "shell"
exec = "ls -la | awk {print $2}"
